### ISSUE TITLE
Memory corruption when using packed strings produced by GDExtension in GDScript

### ISSUE THREAD

**Issue by muskit** [grow-graphics/gd#109]
**GOOS/GOARCH**
linux/amd64

When using (storing) strings produced by my GDExtension in GDScript, random behavior starts to occur with other variables, sometimes resulting in my project crashing.

Minimal reproduction project: https://github.com/muskit/graphics-gd-mem-corrupt-demo

I've attempted to use `String.Readable` in my bindings code, which did not change the outcome. I also wasn't able to use `Packed.Array[String.Readable]` as it wouldn't compile:
```
String.Readable does not satisfy Packed.Type (String.Readable missing in ~byte | ~graphics.gd/variant/Color.RGBA | ~float32 | ~float64 | ~int32 | ~int64 | ~graphics.gd/variant/Vector2.XY | ~graphics.gd/variant/Vector3.XYZ | ~graphics.gd/variant/Vector4.XYZW)`
```

**Comment by Splizard** [comment]
Thanks for reporting, and for the reproduction project! You can use `Packed.Strings` which is the type you were looking to represent. Strings need to be handled differently then value types.

**Comment by Splizard** [comment]
I haven't had a chance to run the repro yet but I've just pushed a fix for packed strings that may help address this issue, if you get the chance to test this, let me know.

**Comment by muskit** [comment]
I built my bindings with the latest version of graphics.gd (21c59578d099) using Packed.Strings and String.Readable. I still get the same issue.

I've updated the repro to use the optimized data types.

**Comment by muskit** [comment]
The latest changes seem to have fixed the corruption in my game project, but not in the repro

**Comment by muskit** [comment]
So it seems that corruption still occurs when the values are used in certain ways, which I cannot consistently reproduce to list out.

Also, if there is no upfront crash, a crash can still occur at some point by other events like changing the window status (ie moving, focusing)

**Comment by Splizard** [comment]
Thanks for the additional details. I plan to repro this with GDB and the address sanitizer enabled.
