### ISSUE TITLE
pong crash (should gd.As return nil, true?)

### ISSUE THREAD

**Issue by adcopeland** [grow-graphics/gd#44]
This is a great project, thanks for making it available!

I noticed an issue with the pong example - if you play it for a little bit and try to hit the ball with the edge of the paddle, you'll eventually (likely one minute or less) get a crash.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x40 pc=0x7ff861248d7a]

goroutine 17 [running, locked to thread]:
main.(*PongPaddle).OnAreaEntered(0xc0001ace70, {{0x0?, 0xc000782030?}, 0x7ff86268e240?}, {{}, {{}, {0x0, 0xc000116b40}})
        C:/grow-test/eg/2d/pong/pong.go:79 +0xda
reflect.Value.call({0x7ff861554f80?, 0xc0001ace70?, 0xc000297a98?}, {0x7ff86176de6f, 0x4}, {0xc0007820f0, 0x2, 0x7ff860)
        C:/Program Files/Go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x7ff861554f80?, 0xc0001ace70?, 0xc000782030?}, {0xc0007820f0?, 0xc000054008?, 0xc00076eec0?})
        C:/Program Files/Go/src/reflect/value.go:380 +0xb9
grow.graphics/gd.registerMethods.func1({{0x344, 0xc000782030}, 0x7ff86268e240}, {0x7ff861577980, 0xc0006a4870}, {0xc000)
        C:/go/pkg/mod/grow.graphics/gd@v0.0.0-20240706222312-056b2f2cb4fc/register_methods.go:77 +0x48b
grow.graphics/gd/gdextension.method_call(0x11?, 0x15, 0x866bdff2d0, 0x1, 0x866bdff020, 0x866bdfefa0)
        C:/go/pkg/mod/grow.graphics/gd@v0.0.0-20240706222312-056b2f2cb4fc/gdextension/gdextension_interface8
```

If I apply this patch it seems to fix it:
```
--- a/2d/pong/pong.go
+++ b/2d/pong/pong.go
@@ -42,7 +42,7 @@ type PongCeilingFloor struct {
 }

 func (cf *PongCeilingFloor) OnAreaEntered(area gd.Area2D) {
-       if ball, ok := gd.As[*PongBall](cf.Temporary, area); ok {
+       if ball, ok := gd.As[*PongBall](cf.Temporary, area); ok && ball != nil {
                ball.Direction = gd.Vector2.Add(ball.Direction, gd.NewVector2(0, gd.Float(cf.BounceDirection))).Normalized()
        }
 }
@@ -75,7 +75,7 @@ func (p *PongPaddle) Process(delta gd.Float) {
 }

 func (p *PongPaddle) OnAreaEntered(godot gd.Context, area gd.Area2D) {
-       if ball, ok := gd.As[*PongBall](godot, area); ok {
+       if ball, ok := gd.As[*PongBall](godot, area); ok && ball != nil {
                ball.Direction = (gd.NewVector2(p.BallDirection, godot.Randf()*2-1)).Normalized()
        }
 }
@@ -85,7 +85,7 @@ type PongWall struct {
 }

 func (w *PongWall) OnAreaEntered(godot gd.Context, area gd.Area2D) {
-       if ball, ok := gd.As[*PongBall](godot, area); ok {
+       if ball, ok := gd.As[*PongBall](godot, area); ok && ball != nil {
                ball.Reset()
        }
 }
```

It seems like `gd.As` can return nil, true.

If that's intentional, the example should be updated. If it's not intentional, maybe a check before returning? Or perhaps there's some deeper invariant that should be corrected?

In case it matters, I'm using a Windows 11 amd64 laptop with go 1.22.5 and godot 4.2.2
```
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650
```

**Comment by Splizard** [comment]
This is definitely a bug, thankyou for finding, I've pushed something that may fix it.

**Comment by adcopeland** [comment]
It still happens for me, but it feels like it might be harder to reproduce now it's hard to say.

I changed to this patch so it's easier to verify:
```
--- a/2d/pong/pong.go
+++ b/2d/pong/pong.go
@@ -1,6 +1,7 @@
 package main

 import (
+       "fmt"
        "grow.graphics/gd"
        "grow.graphics/gd/gdextension"
 )
@@ -43,6 +44,9 @@ type PongCeilingFloor struct {

 func (cf *PongCeilingFloor) OnAreaEntered(area gd.Area2D) {
        if ball, ok := gd.As[*PongBall](cf.Temporary, area); ok {
+               if ball == nil {
+                       fmt.Println("BALL IS NIL")
+               }
                ball.Direction = gd.Vector2.Add(ball.Direction, gd.NewVector2(0, gd.Float(cf.BounceDirection))).Normalized()
        }
 }
@@ -76,6 +80,9 @@ func (p *PongPaddle) Process(delta gd.Float) {

 func (p *PongPaddle) OnAreaEntered(godot gd.Context, area gd.Area2D) {
        if ball, ok := gd.As[*PongBall](godot, area); ok {
+               if ball == nil {
+                       fmt.Println("BALL IS NIL")
+               }
                ball.Direction = (gd.NewVector2(p.BallDirection, godot.Randf()*2-1)).Normalized()
        }
 }
@@ -86,6 +93,9 @@ type PongWall struct {

 func (w *PongWall) OnAreaEntered(godot gd.Context, area gd.Area2D) {
        if ball, ok := gd.As[*PongBall](godot, area); ok {
+               if ball == nil {
+                       fmt.Println("BALL IS NIL")
+               }
                ball.Reset()
        }
 }
```

and I do see BALL IS NIL before the panic.

I don't have a great way to verify I really did build with the update in place but I ran go get -u grow.graphics/gd and it updated to  `v0.0.0-20240710064531-edc03e71dbe9` then I reran using `gd run` so I think I have it.

**Comment by adcopeland** [comment]
I can confirm that in a crash scenario, this line:
https://github.com/grow-graphics/gd/blob/master/internal/oop.go#L121

returned `true, nil` but I was unable to compare `var zero T` to the result to check due to `incomparable types in type set`.

**Comment by Splizard** [comment]
That's the weird thing, any Go-backed instances should be checked at the beginning of the function. The underlying pointer must be different. In which case maybe the object ID needs to be used as the map key.

**Comment by adcopeland** [comment]
I see what you mean. I assume the `[2]uintptr` from mmm.Get is the numeric pointer value and then the refcount?

I can confirm when the crash happens it is the normal return, not the empty object return (i.e. https://github.com/grow-graphics/gd/blob/master/gdextension/gdextension_interface.go#L1941)

Given line 1936 checks for the numeric cast to be 0, it does seem impossible. Maybe it's my machine somehow.

I'm using `gcc (tdm64-1) 10.3.0` which might be questionable. It seemed to work well for me in other situations and resulting binaries are pretty seamless on windows, but I'll try something else and see if the problem goes away.

**Comment by Splizard** [comment]
@adcopeland I'm unable to produce this on my system, it may be useful to add some prints / use a debugger to inspect what the value is to figure out what is happening here. What does `reflect.TypeOf(p.Temporary.Variant(area).Interface(p.Temporary))` report for example?

**Comment by adcopeland** [comment]
I tried `zig cc` as my compiler for cgo and observed the same behavior.

```
toprint := reflect.TypeOf(p.Temporary.Variant(area).Interface(p.Temporary))
fmt.Printf("%T %v\n", toprint, toprint)
```

prints in the error case: `*reflect.rtype gd.Object`

If I print that always instead of just when ball is nil, oddly the ball seems to disappear on the first bounce.
```

 func (p *PongPaddle) OnAreaEntered(godot gd.Context, area gd.Area2D) {
        if ball, ok := gd.As[*PongBall](godot, area); ok {
+               toprint := reflect.TypeOf(p.Temporary.Variant(area).Interface(p.Temporary))
+               fmt.Printf("%T %v\n", toprint, toprint)
                ball.Direction = (gd.NewVector2(p.BallDirection, godot.Randf()*2-1)).Normalized()
        }
 }
```

I'll do some more digging and let you know if I find anything useful.

**Comment by Splizard** [comment]
Might be resolved?

**Comment by adcopeland** [comment]
yes, it does appear to be resolved. Closing.
